### ISSUE TITLE
setup controllers (pole target issue?)

### ISSUE THREAD

**Issue by DeWolfePilot** [marekzajac97/bf2-blender#1]
When check **"setup controller"** rig changes position from original one so elbows pointing pole target wrongly.

Blender 3.6

https://www.youtube.com/watch?v=BXdCzULJlEc

**Comment by marekzajac97** [comment]
Try manually tweaking the "pole angle", that should fix it. You will find it inside the 'Bone constraint properties' tab after selecting `R_ullna` bone in Pose Mode (you need to right mouse click -> unhide and reselect the bone first for it to show up, it's bugged)

Not a whole lot I can do about it in the plugin. It's quite difficult (if not impossible) to automatically set up an IK that perfectly matches the imported animation, I have some ideas to improve it (but it is low priority for now).

**Comment by DeWolfePilot** [comment]
Ok, but if only it's not reseting ik modifier params on each anim's import...  Btw great tool, really enjoy it, hope you'll not abandon it. Cheers.
