### ISSUE TITLE
BF2-hud-fix-related request

### ISSUE THREAD

**Issue by Mitch037** [marekzajac97/bf2-blender#3]
Hello,
I'm sorry for making the mess here but I'm not sure if you still look at the BF2-hud-fix repo and its issues tab. About a year ago I added a ticket with a request related to the fix. If you could take a look at it I would be very grateful. The ticket is [HERE](https://github.com/marekzajac97/BF2-HUD-fix/issues/5).

**Comment by marekzajac97** [comment]
roger
